services:
  nginx:
    image: nginx:1.19.4
    depends_on:
      - SpotifyAppUI
      - APIGateway
    volumes:
      - ./nginx/default.local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'

  SpotifyAppUI:
   image: jafrin/spotify-app-ui:v1
   ports:
    - "4000:3000"
    
  APIGateway:
   image: jafrin/apigateway
   ports:
    - "5015:80"
   links:
    - AuthService
    - UserProfileService
    - WishlistService
    - MusicService
   depends_on:
    - AuthService
    - UserProfileService
    - WishlistService
    - MusicService
    
  AuthService:
   image: jafrin/authmicroservice:v1
   environment:
    - CONNECTIONSTRINGS__AuthCon=Data Source=sqldb;Initial Catalog=AuthServiceDB;User Id=sa;Password=pass@123
    - Kafka__Server=kafka
   depends_on:
    - sqldb
    - kafka
   ports:
    - "5010:80"

  UserProfileService:
   image: jafrin/userprofilemicroservice:v1
   environment:
    - MongoDB__ConnectionString=mongodb://mongodbserver
    - Kafka__Server=kafka
   depends_on:
    - mongodbserver
    - kafka
   ports:
    - "5011:80"

  WishlistService:
   image: jafrin/wishlistmicroservice:v1
   environment:
    - MongoDB__ConnectionString=mongodb://mongodbserver
   depends_on:
    - mongodbserver
   ports:
    - "5012:80"

  MusicService:
   image: jafrin/musicmicroservice:v1
   environment:
    - MongoDB__ConnectionString=mongodb://mongodbserver
   depends_on:
    - mongodbserver
   ports:
    - "5013:80"

  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=pass@123
      - ACCEPT_EULA=Y
  
  mongodbserver:
    image: mongo
    ports:
      - 5014:27017

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1